CREATE TABLE "country_dev_trends" (
	"country_dev_trend_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "country_dev_trends_country_dev_trend_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"country" text DEFAULT '' NOT NULL,
	"country_name" text DEFAULT '' NOT NULL,
	"region" text DEFAULT '' NOT NULL,
	"office" text DEFAULT '' NOT NULL,
	"category" text DEFAULT '' NOT NULL,
	"sector" text DEFAULT '' NOT NULL,
	"title" text DEFAULT '' NOT NULL,
	"content_1" text DEFAULT '' NOT NULL,
	"content_2" text DEFAULT '' NOT NULL,
	"content_3" text DEFAULT '' NOT NULL,
	"content_4" text DEFAULT '' NOT NULL,
	"content_5" text DEFAULT '' NOT NULL,
	"covid19_related" text DEFAULT '' NOT NULL,
	"source" text DEFAULT '' NOT NULL,
	"link" text DEFAULT '' NOT NULL,
	"published_date" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dispatch_agencies" (
	"dispatch_agency_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dispatch_agencies_dispatch_agency_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"country" text DEFAULT '' NOT NULL,
	"agency_name_ko" text DEFAULT '' NOT NULL,
	"agency_name_en" text DEFAULT '' NOT NULL
);
